[package]
name = "space-invaders"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = ["file_watcher"] }
rand = "0.9.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
