[package]
name = "space-invaders"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.2"
bevy_sprite = { version = "0.17.2" , features = ["bevy_picking", "bevy_sprite_picking_backend", "bevy_text", "bevy_window"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
