[package]
name = "space-invaders"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = ["track_location"] }
rand = "0.9.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1
